### ISSUE TITLE
Check that a capsule's signature fields are annotated with @Imports

### ISSUE THREAD

**Issue by dwtj** [paninij/paninij#125]
Check that if a capsule has a signature as a field then it is annotated with `@Imports` (and not `@Local`).

The following code (a slightly modified version of `org.paninij.examples.helloworld.GreeterTemplate`) should fail a check:

``` .java
@Capsule
class GreeterTemplate
{
    String message;
    @Imports Stream s1;
    @Local Stream s2;
    ...
```

`Stream` is a signature. An error should be thrown on account of `s2`, because the system does not know the concrete capsule type to instantiate for this local.

I think that a `@BadTemplate` should be added to `org.paninij.proc.check.capsule.fields`.

**Comment by dwtj** [comment]
My guess is that this should be implemented as another *template* check, not just a capsule check or a signature check.

**Comment by jlmaddox** [comment]
Now that we have a system of multiple rounds of checks set up, this issue should be solved.
