### ISSUE TITLE
Signatures should always be interfaces

### ISSUE THREAD

**Issue by jlmaddox** [paninij/paninij#159]
Currently there is no check such that signatures must be interfaces, and they can be defined as classes or abstract classes. However, doing so causes an error in the annotation processor and breaks a project's build. We need to add a check for this to prevent this from happening.

**Comment by ekuntz11** [comment]
@jlmaddox I think the check for this issue already exists. I also experimented with attempting to annotate both an abstract class and class with @Signature, and got a compilation error (as expected).
 https://github.com/paninij/paninij/blob/master/core/proc/src/main/java/org/paninij/proc/check/signature/SignatureCheck.java

**Comment by jlmaddox** [comment]
@ekuntz11 This seems to have already been fixed then, but looking at the code I'm not sure I like the idea of using default interface methods. Is there any reason SignatureCheck and CapsuleCheck should be interfaces with default methods as opposed to abstract classes?

**Comment by ekuntz11** [comment]
@jlmaddox That is a good question. I am not sure. I will look into it. If desired, I can work on changing the SignatureCheck and CapsuleCheck from interfaces to abstract classes, in addition to changing the default methods (checkCapsule and checkSignature).

**Comment by jlmaddox** [comment]
This bug has been fixed by a previous commit.
