### ISSUE TITLE
Maven deploy to Maven Central for public consumption

### ISSUE THREAD

**Issue by ddmills** [paninij/paninij#50]

**Comment by dwtj** [comment]
Some resources:

- [Guide: Central Repository Upload](https://maven.apache.org/guides/mini/guide-central-repository-upload.html)
- [Required POM Info](http://central.sonatype.org/pages/requirements.html)

It looks like we're going to need a PGP keypair with which to sign uploaded artifacts. Who should the owner be? Dr. Rajan? How and where should it be stored?

**Comment by dwtj** [comment]
Could someone else cover this one?

**Comment by hridesh** [comment]
Let us revisit this. I am happy to sign it with my PGP key.

**Comment by dwtj** [comment]
The first version of @PaniniJ to be hosted on Maven central was v0.2.2.

See https://search.maven.org/#search%7Cga%7C1%7Corg.paninij

Support for this feature was added as of commit 60418152.
